In [38]:
import numpy as np

n=10
w= np.random.randint(1,100,size=n)
print(w)
x = np.random.randint(1,100, size=n)
print(x)
h_score = np.random.randint(1,100,size=n)
print(h_score)



loses =[]

for i in range(len(w)):
    for j in range(len(x)):
        y = (w[i]*x[j]) - h_score[j]
        print(y)
        loses.append(y)
   
cost = np.sum(loses) / len(loses)
print(cost) 

[59 95 80 29 36  6 51 77 51 65]
[67 91 53 78 30 54 93 77 49 70]
[38 40 20 19 42 91 78 76 80 63]
3915
5329
3107
4583
1728
3095
5409
4467
2811
4067
6327
8605
5015
7391
2808
5039
8757
7239
4575
6587
5322
7240
4220
6221
2358
4229
7362
6084
3840
5537
1905
2599
1517
2243
828
1475
2619
2157
1341
1967
2374
3236
1888
2789
1038
1853
3270
2696
1684
2457
364
506
298
449
138
233
480
386
214
357
3379
4601
2683
3959
1488
2663
4665
3851
2419
3507
5121
6967
4061
5987
2268
4067
7083
5853
3693
5327
3379
4601
2683
3959
1488
2663
4665
3851
2419
3507
4317
5875
3425
5051
1908
3419
5967
4929
3105
4487
3579.68


In [40]:
data = np.random.rand(20, 2)
X = data[:, 0]
Y = data[:, 1]
print("data",data)
print(X)

weights = np.array([0.5, 0.54, 0.004,0.786])
b = 2

for m in weights:
    Y_pred = m * X + b
    loss = 0.5*(Y - Y_pred)**2
    cost = np.mean(loss)
    print(f"Weight: {m}, Loss per row: {loss}, Total Cost: {cost}")

data [[0.92758683 0.2123521 ]
 [0.23405963 0.34453377]
 [0.5650182  0.29572964]
 [0.36722386 0.24721449]
 [0.58635178 0.27935175]
 [0.79453006 0.83606938]
 [0.4103789  0.68216951]
 [0.141533   0.540282  ]
 [0.98258474 0.80333167]
 [0.80812906 0.21033529]
 [0.42643437 0.84020286]
 [0.60327289 0.66439753]
 [0.83379576 0.21113886]
 [0.59474183 0.60155576]
 [0.35776386 0.42621366]
 [0.93477409 0.29658758]
 [0.56034828 0.32310762]
 [0.49675848 0.99349272]
 [0.86173251 0.3057247 ]
 [0.05192995 0.51899157]]
[0.92758683 0.23405963 0.5650182  0.36722386 0.58635178 0.79453006
 0.4103789  0.141533   0.98258474 0.80812906 0.42643437 0.60327289
 0.83379576 0.59474183 0.35776386 0.93477409 0.56034828 0.49675848
 0.86173251 0.05192995]
Weight: 0.5, Loss per row: [2.53449399 1.57087111 1.97364631 1.87481752 2.02774383 1.21866593
 1.15979487 1.17119141 1.42460567 2.40622398 0.94258417 1.34027564
 2.43268644 1.43789452 1.53592304 2.35618516 1.91505467 0.78737009
 2.25811331 1.13548441], Total Cost: 1.67