In [1]:
import numpy as np

n=10
w= np.random.randint(1,100,size=n)
print(w)
x = np.random.randint(1,100, size=n)
print(x)
h_score = np.random.randint(1,100,size=n)
print(h_score)



loses =[]

for i in range(len(w)):
    for j in range(len(x)):
        y = (w[i]*x[j]) - h_score[j]
        print(y)
        loses.append(y)
   
cost = np.sum(loses) / len(loses)
print(cost) 

[ 4 15 59 89 43 17 37  4 17 56]
[49 25 19  9 43 90 66 33 98 55]
[20 96  4 21 23 72 80 31  7 81]
176
4
72
15
149
288
184
101
385
139
715
279
281
114
622
1278
910
464
1463
744
2871
1379
1117
510
2514
5238
3814
1916
5775
3164
4341
2129
1687
780
3804
7938
5794
2906
8715
4814
2087
979
813
366
1826
3798
2758
1388
4207
2284
813
329
319
132
708
1458
1042
530
1659
854
1793
829
699
312
1568
3258
2362
1190
3619
1954
176
4
72
15
149
288
184
101
385
139
813
329
319
132
708
1458
1042
530
1659
854
2724
1304
1060
483
2385
4968
3616
1817
5481
2999
1617.17


In [2]:
data = np.random.rand(20, 2)
X = data[:, 0]
Y = data[:, 1]
print("data",data)
print(X)

weights = np.array([0.5, 0.54, 0.004,0.786])
b = 2

for m in weights:
    Y_pred = m * X + b
    loss = 0.5*(Y - Y_pred)**2
    cost = np.mean(loss)
    print(f"Weight: {m}, Loss per row: {loss}, Total Cost: {cost}")

data [[0.8672949  0.39461421]
 [0.04373269 0.10132041]
 [0.8650915  0.92535986]
 [0.53685179 0.18939622]
 [0.48783893 0.31632836]
 [0.25221021 0.8375774 ]
 [0.88262171 0.45204834]
 [0.32486555 0.12021368]
 [0.46814043 0.25764211]
 [0.34486915 0.32149811]
 [0.04093641 0.97731451]
 [0.74120449 0.58918886]
 [0.06562411 0.27948312]
 [0.51775573 0.08318602]
 [0.06043058 0.54516919]
 [0.87977407 0.57966563]
 [0.08528099 0.63271683]
 [0.02057531 0.78293115]
 [0.17596354 0.6809923 ]
 [0.30555468 0.34820579]]
[0.8672949  0.04373269 0.8650915  0.53685179 0.48783893 0.25221021
 0.88262171 0.32486555 0.46814043 0.34486915 0.04093641 0.74120449
 0.06562411 0.51775573 0.06043058 0.87977407 0.08528099 0.02057531
 0.17596354 0.30555468]
Weight: 0.5, Loss per row: [2.07882829 1.84424835 1.13580465 2.16118218 1.85780372 0.83015181
 1.97858268 2.08532943 1.95313402 1.7129829  0.54408481 1.58671682
 1.53708118 2.3668175  1.10268096 1.73021185 0.99394237 0.753202
 0.98980968 1.62823923], Total Cost: 1.5435