In [4]:
import numpy as np
from numpy.linalg import norm

In [16]:
matrix = np.ones((5, 5))
matrix


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
matrix[1:4, 1:4] = 0

matrix

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
matrix[2, 2] = 9
matrix

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
np_array = np.random.rand(10, 10)
np_array

array([[0.56982968, 0.36374672, 0.18381937, 0.23373009, 0.10376922,
        0.00193247, 0.27935213, 0.29483524, 0.57843561, 0.67324917],
       [0.09015762, 0.90694815, 0.73724167, 0.63528319, 0.32155692,
        0.09294526, 0.54760546, 0.56141738, 0.08500127, 0.75321123],
       [0.76186166, 0.4261865 , 0.62312812, 0.91466572, 0.36376136,
        0.01354014, 0.18350085, 0.31439367, 0.78782293, 0.35548625],
       [0.79719645, 0.40998717, 0.13701665, 0.98410967, 0.28164898,
        0.5833933 , 0.49458175, 0.83920452, 0.75223793, 0.44449465],
       [0.6936277 , 0.21002735, 0.70974989, 0.56476347, 0.37111412,
        0.27063098, 0.15007573, 0.64845021, 0.71929084, 0.48041641],
       [0.28562763, 0.78918384, 0.80258783, 0.72730557, 0.04884732,
        0.87752132, 0.55225956, 0.17259745, 0.05170283, 0.88594302],
       [0.00599732, 0.26168053, 0.25169789, 0.01276406, 0.60070317,
        0.05239092, 0.10489706, 0.57020849, 0.72248114, 0.82705068],
       [0.17865163, 0.10128567, 0.1810513

In [6]:
first = np_array[0]
first

array([0.56982968, 0.36374672, 0.18381937, 0.23373009, 0.10376922,
       0.00193247, 0.27935213, 0.29483524, 0.57843561, 0.67324917])

In [7]:
nine_rows = np_array[1:]
nine_rows

array([[0.09015762, 0.90694815, 0.73724167, 0.63528319, 0.32155692,
        0.09294526, 0.54760546, 0.56141738, 0.08500127, 0.75321123],
       [0.76186166, 0.4261865 , 0.62312812, 0.91466572, 0.36376136,
        0.01354014, 0.18350085, 0.31439367, 0.78782293, 0.35548625],
       [0.79719645, 0.40998717, 0.13701665, 0.98410967, 0.28164898,
        0.5833933 , 0.49458175, 0.83920452, 0.75223793, 0.44449465],
       [0.6936277 , 0.21002735, 0.70974989, 0.56476347, 0.37111412,
        0.27063098, 0.15007573, 0.64845021, 0.71929084, 0.48041641],
       [0.28562763, 0.78918384, 0.80258783, 0.72730557, 0.04884732,
        0.87752132, 0.55225956, 0.17259745, 0.05170283, 0.88594302],
       [0.00599732, 0.26168053, 0.25169789, 0.01276406, 0.60070317,
        0.05239092, 0.10489706, 0.57020849, 0.72248114, 0.82705068],
       [0.17865163, 0.10128567, 0.18105131, 0.45213738, 0.93036188,
        0.65513753, 0.43344264, 0.3732692 , 0.42164698, 0.4902714 ],
       [0.12012548, 0.83424607, 0.2054442

In [8]:
nine_rows[0]

array([0.09015762, 0.90694815, 0.73724167, 0.63528319, 0.32155692,
       0.09294526, 0.54760546, 0.56141738, 0.08500127, 0.75321123])

In [9]:
  
results = []
  
for i in range(len(nine_rows)):
    res = nine_rows[i]
    dot_p = np.dot(first,res)
    mod = norm(first) + norm(res)
    cosine = dot_p / mod
    results.append(cosine * 100)
    
results

[52.74742598107086,
 60.612508300693854,
 62.60188441541851,
 60.47467145276614,
 50.64053565611458,
 52.05084097140937,
 42.90575806187826,
 42.14162598921344,
 56.50115471468319]